// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/login" | "/oauth/authorize" | "/products" | "/products/[id]" | "/products/[id]/audiences" | "/products/[id]/brand" | "/products/[id]/channels" | "/products/[id]/claude" | "/products/[id]/connections" | "/products/[id]/connections/[cid]" | "/products/[id]/goals" | "/products/[id]/leads" | "/products/[id]/library" | "/products/[id]/library/[personId]" | "/products/[id]/logs" | "/products/[id]/providers" | "/products/[id]/review" | "/products/[id]/routines" | "/products/[id]/settings" | "/products/[id]/sources" | "/products/[id]/templates" | "/products/[id]/templates/[tid]" | "/signup"
type AppRouteHandlerRoutes = "/api/cron/tick" | "/api/mcp" | "/api/notifications" | "/api/oauth/callback" | "/api/oauth/google/callback" | "/api/oauth/register" | "/api/oauth/token" | "/api/t/[kind]/[id]" | "/api/test/leads" | "/api/u/[id]" | "/api/wellknown/oauth-authorization-server" | "/api/wellknown/oauth-protected-resource"
type PageRoutes = never
type LayoutRoutes = "/" | "/products/[id]"
type RedirectRoutes = never
type RewriteRoutes = "/.well-known/oauth-authorization-server" | "/.well-known/oauth-protected-resource" | "/.well-known/oauth-protected-resource/api/mcp"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/.well-known/oauth-authorization-server": {}
  "/.well-known/oauth-protected-resource": {}
  "/.well-known/oauth-protected-resource/api/mcp": {}
  "/api/cron/tick": {}
  "/api/mcp": {}
  "/api/notifications": {}
  "/api/oauth/callback": {}
  "/api/oauth/google/callback": {}
  "/api/oauth/register": {}
  "/api/oauth/token": {}
  "/api/t/[kind]/[id]": { "kind": string; "id": string; }
  "/api/test/leads": {}
  "/api/u/[id]": { "id": string; }
  "/api/wellknown/oauth-authorization-server": {}
  "/api/wellknown/oauth-protected-resource": {}
  "/login": {}
  "/oauth/authorize": {}
  "/products": {}
  "/products/[id]": { "id": string; }
  "/products/[id]/audiences": { "id": string; }
  "/products/[id]/brand": { "id": string; }
  "/products/[id]/channels": { "id": string; }
  "/products/[id]/claude": { "id": string; }
  "/products/[id]/connections": { "id": string; }
  "/products/[id]/connections/[cid]": { "id": string; "cid": string; }
  "/products/[id]/goals": { "id": string; }
  "/products/[id]/leads": { "id": string; }
  "/products/[id]/library": { "id": string; }
  "/products/[id]/library/[personId]": { "id": string; "personId": string; }
  "/products/[id]/logs": { "id": string; }
  "/products/[id]/providers": { "id": string; }
  "/products/[id]/review": { "id": string; }
  "/products/[id]/routines": { "id": string; }
  "/products/[id]/settings": { "id": string; }
  "/products/[id]/sources": { "id": string; }
  "/products/[id]/templates": { "id": string; }
  "/products/[id]/templates/[tid]": { "id": string; "tid": string; }
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/products/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
